version: "3.9"
services:
  rosys:
    build: .
    volumes:
      - ./:/app
      - ~/.rosys:/home/zauberzeug/.rosys
      - ./../lizard:/home/zauberzeug/.lizard
      # - ./../rosys:/rosys
      # - ./../nicegui/nicegui:/usr/local/lib/python3.11/site-packages/nicegui
    devices:
      - "/dev/bus/usb/001/*:/dev/bus/usb/001/*"
    network_mode: host
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Amsterdam

    hostname: docker
    cap_add:
      - SYS_NICE
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "100"
